export type Media = { id: string; step: number; url: string };
export type Snapshot = {
  room_id: string;
  round_id: string;
  revision: number;
  code: string;
  mode: "rehearsal" | "live";
  phase: string;
  step: number;
  role: string;
  is_host: boolean;
  players: { role: string; name: string; is_host: boolean }[];
  own: { prompt?: string; guess?: string };
  media: Media[];
  guess_count: number;
  token_limit: number;
  can_start: boolean;
  start_blocked?: string;
  closing: boolean;
  error?: string;
  unscored: boolean;
  join_url: string;
  generation_elapsed?: number;
  relay_remaining_ms: number | null;
  remaining_attempts?: number;
  cleanup_pending: boolean;
  scripted_text?: string;
  reveal_index: number | null;
  results_revealed: boolean;
  chain?: { prompt: string; player: string; role: string; media: Media }[];
  results?: {
    role: string;
    player: string;
    guess: string;
    points: number | null;
    winner: boolean;
  }[];
};
